version: '3'

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /local/storage/backup/db:/tmp/backup/db
    environment:
      POSTGRES_DB: masiaventura
      POSTGRES_USER: masiaventura
    ports:
      # aunque no es necesario exponer la base de datos hacia fuera
      # puede ser util para consultarla con un IDE
      - 5432:5432

  manager:
    image: masiaventura-docker-public.bintray.io/manager:0.1.0
    volumes:
      # para asegurarnos de que la hora del contenedor 
      # de Docker sigue la hora de la maquina host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # tus ficheros estaran guardandose en /local/storage/
      # dentro de tu maquina
      - /local/storage/run:/tmp/kk
      - /local/storage/backup/files:/tmp/backup/files
    environment:
      # admin
      ADMIN_NAME: admin
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password      
      # configuracion de base de datos
      DATABASE_URL: jdbc:postgresql://db/masiaventura
      DATABASE_DRIVER_CLASSNAME: org.postgresql.Driver
      DATABASE_USERNAME: masiaventura
      DATABASE_PASSWORD: masiaventura
    ports:
      # queremos que el servidor escuche en el puerto 9000
      - 9000:8080
    depends_on:
      - db
